name: Axe Accessibility Check

on:
  pull_request:
    branches:
      - main

jobs:
  axe:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Install axe-core CLI
        run: npm install -g @axe-core/cli

      - name: Start Application
        run: npm start & npx wait-on http://localhost:5173

      - name: Run Axe Accessibility Tests and Capture Output
        id: axe_results
        run: |
          axe_output=$(axe http://localhost:5173)
          echo "::set-output name=axe_output::$axe_output"

      - name: Comment PR with Axe Accessibility Check Results
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            **Axe Accessibility Check Results:**

            ```
            ${{ steps.axe_results.outputs.axe_output }}
            ```

          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

      - name: Exit
        run: exit 0
