name: Axe Accessibility Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  axe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.6.1    

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Install axe-core CLI
        run: npm install -g @axe-core/cli

      - name: Start Application
        run: npm start & npx wait-on http://localhost:5173

      - name: Run Axe
        run: axe http://localhost:5173 --exit
