name: CI
on:
  push:
    branches: []
  pull_request:
    branches: []
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest  # or specify a specific version if needed
          install-dependencies: true  # optional, installs required dependencies
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: run Lighthouse CI
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: lhci autorun
