name: Pa11y Action

on:
  pull_request:
    branches: []

jobs:
  pa11y:
    name: Pa11y
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install npm packages and build
        run: |
          npm install
          npm run build

      - name: Start Application
        run: |
          npm start &

      - name: Wait for Application to Start
        uses: trendyol/wait-action@v1
        with:
          url: 'http://localhost:5173'

      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Run Pa11y Tests
        run: pa11y http://localhost:5173
