name: Lighthouse
on:
  pull_request:
    branches: []
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: run Lighthouse CI
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: lhci autorun