name: Pa11y Action

on:
  pull_request:
    branches: []

jobs:
  pa11y:
    name: Pa11y
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install wait-on
        run: npm install wait-on

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Install Pa11y
        run: npm install -g pa11y

      - name: Start application
        run: npm start & npx wait-on http://localhost:5173

      - name: Run Pa11y CI and Save Output
        run: npm run pa11y-ci 2>&1 | tee pa11y_output.txt

      - name: Read Pa11y output file
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.txt

      - name: Comment on pull request with Pa11y testing results
        uses: thollander/actions-comment-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
          message: |
            <details>
              <summary>Pa11y Testing Results</summary>

              ```
              ${{ steps.pa11y_output.outputs.content }}
              ```

            </details>

      - name: Check for Pa11y failures
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the Pa11y CI step in the workflow for details."
          exit 1
