name: Pa11y Action

on:
  pull_request:
    branches: []

jobs:
  pa11y:
    name: Pa11y
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install wait-on
        run: npm install wait-on

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Start application
        run: npm start & npx wait-on http://localhost:5173

      - name: Run pa11y-ci and Save Output
        run: |
          npm install -g pa11y-ci
          pa11y-ci --reporter=json > pa11y_results.json

      - name: Comment PR with Pa11y Results
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pa11y_results.json
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

      - name: Exit
        run: exit 0