name: Pa11y Action
on:
  push:
    branches: []
  pull_request:
    branches: []
jobs:
  pa11y:
    name: Pa11y
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:5173