on: [pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: browser-actions/setup-chrome@latest
    - uses: Hesedi3l/pa11y-actions@v1
      with:
        start: start
        port: '5173'